// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 运行时必须通过环境变量设置，支持默认值作为兜底
    url: process.env["DATABASE_URL"] ?? "file:/app/data/prod.db",
  },
});
